### ISSUE TITLE
Tesis vs. Disertación

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#10]
Sé que en diferentes países de América Latina se utiliza indistintamente la palabra "tesis" o "disertación" para referir el trabajo final de grado. Sugiero usar "tesis" para homologar ¿qué opinan?

**Comment by MpaulaL** [comment]
No me he encontrado con aquella palabra, pero lo tendré en cuenta.

En cambio, sí me encontré con el término high-school - es entenddido por todos si lo traduzco a ensegnanza secundaria?

**Comment by rosariorogel** [comment]
No exactamente, en el caso de México tenemos "cuatro ciclos" educativos previos al Universitario (College):
1. Preescolar (2 o 3 años)
2. Primaria (6 años)
3. Secundaria (3 años)
4. Preparatoria (3 años)

No sé cómo sea en el resto de América Latina, quizá el término "estudios preuniversitarios" sea el menos usado, pero es lo único que me parece podría homologar ¿cómo lo ven?

**Comment by cvilchesfurio** [comment]
Estuve revisando el Glosario de la UNESCO, y dice lo siguiente:
**Enseñanza secundaria (niveles 2 y 3 de la CINE).**
Los programas del primer ciclo de la enseñanza secundaria (nivel 2 de la CINE) están destinados por regla general a continuar los programas básicos de primaria, pero este nivel de enseñanza suele centrarse más en las disciplinas enseñadas y exige a menudo docentes más especializados en cada materia. El final de este ciclo suele coincidir con la terminación de la enseñanza obligatoria. Los programas del segundo ciclo de secundaria (nivel 3 de la CINE) constituyen la fase final de este tipo de enseñanza en la mayoría de los países. En este ciclo, los programas se suelen estructurar aún más por disciplinas que en el nivel 2 y los  docentes deben poseer en general un título más calificado o especializado que en ese nivel. 
http://www.unesco.org/education/GMR/2007/es/glosario.pdf

**Comment by cvilchesfurio** [comment]
Clasificación Internacional Normalizada de la Educación, CINE 2011 
http://unesdoc.unesco.org/images/0022/002207/220782s.pdf

**Comment by cvilchesfurio** [comment]
Me parece que Educación Secundaria sería el termino correcto. En el Tesauro de Naciones Unidas también aparece Educación Secundaria https://lib-thesaurus.un.org/LIB/DHLUNBISThesaurus.nsf/MultiSpa/D7CD980C2DEF5D9385256AA0005FC6F0?OpenDocument

**Comment by cvilchesfurio** [comment]
De acuerdo con tesis!

**Comment by rosariorogel** [comment]
A partir de la explicación que provee Claudia, la traducción más adecuada podría ser "secundaria"; sin embargo, dado que en algunos casos (como el mexicano) no existe una correspondencia con los ciclos, sugiero traducir "high school" como "educación secundaria", pero agregar una nota a pie de página de la traducción donde se aclare lo que acaba de señalar Claudia y se mencione que en el caso mexicano "high school" corresponde a lo que se conoce como "educación preparatoria".
