### ISSUE TITLE
Agregar notas para el caso de América Latina 

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#11]
Dejé marcado en formato de "quotes" en Github las sugerencias para agregar información específica para el caso de América Latina, agradeceré si me dan su opinión acerca de la pertinencia de ello (y sobre todo de dónde colocarlas).

**Comment by cvilchesfurio** [comment]
Rosario, en la Guía de traducción se recomienda:
<li>	Incorporar inciativas, experiencias, ejemplos, referencias bibliográficas que reflejen  la perspectiva de la región latinoamericana y caribeña y de los países hispanoparlantes. Para ello, agregar una nota a pie de página con la siguiente leyenda: "(*) Información añadida a la versión en español".</li>
<li> Respecto de la incoporación de nuevas referencias bibliográficas, usar el estilo de citación APA. No olvidar colocar la nota "(*) Información añadida a la versión en español". El coordinador consolidará, en el proceso de edición final, la bibliografía incorporada por todos los colaboradores y las subirá a la bibliografía general y al grupo disponible en Zotero.</li>

**Comment by rosariorogel** [comment]
Sí, ya lo hice así, agregué los comentarios sobre iniciativas de leyes de AA para América Latina y dejé anotada la leyenda a pie de página.

Gracias
