### ISSUE TITLE
Sugerencia sobre la forma de trabajo

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#13]
Durante la sesión webex nos sugirieron que editáramos directamente el documento maestro, y que tradujéramos párrafo por párrafo al español, posterior al texto en inglés. Intenté hacerlo, pero era bastante confuso.

Por esa razón pedí apoyo a mi hermano (que conoce muy bien de estas cosas) y él me sugirió abrir una rama y trabajar directamente en un ambiente local, en archivos por separado en Español e Inglés, y posteriormente actualizar y solicitar un "pull request" al administrador (es decir Claudia) quien tendría que aprobar o rechazar mi propuesta de traducción. Estoy marcando la versión en Español con un sufijo "ES".

Ya he mandado el primer "pull request".

Quedo en espera de sus comentarios acerca de esta forma de trabajo y les comento que mi hermano está en la mejor disposición de apoyarnos en el uso adecuado del Github, quizá si requerimos una sesión de asesoría sería posible, siempre y cuando consideremos que él vive en Londres y sería preciso ajustarnos a sus horarios.

Saludos

**Comment by MpaulaL** [comment]
Rosario, gracias por compartir tu estrategia. Yo estoy trabajando en Atom y he ido traduciendo párrafo a párrafo como sugirió Claudia. Desde Atom puedes 'push' el texto a GitHub, ya sea a una rama o al documento maestro. Supongo que al final Claudia tiene que comunicarnos lo que sea más fácil para hacer la revisión posteriormente?

**Comment by cvilchesfurio** [comment]
Hola Rosario, efectivamente existe esa otra forma de edición: haciendo un Pull Request. Consulté en su momento con Helene Brinken, y me sugirió el modo que estamos trabajando, directamente en el texto. Si te queda más cómodo hacer Pull Request no hay problema, depende de cada uno. Lo importante es que me cuenten cuando consideren que el texto traducido está realmente listo para su revisión final. Si alguno termina antes del 31 de octubre, le agradecería me informe, para avanzar en la revisión.

**Comment by rosariorogel** [comment]
Yo ya acabe toda mi parte: Abrí una nueva rama e hice un "Pull Request" con todos los cambios, lo puedes ver en tu estado de administrador. Lo único que me queda pendiente es incluir el comentario de "patient innovación" y listo. Con ello estaría concluyendo la parte que me fue asignada, y me pongo a su disposición por si creen que les puedo apoyar en algo más ;)

**Comment by rosariorogel** [comment]
Por cierto, yo estoy trabajando con Typora que –al igual que Atom que usa Paula– permite hacer "commit" directamente a GitHub. Lo único que sugería (y así es como yo lo hice) fue trabajar en "ramas" en lugar de manipular directamente el "master", pues ello le permitirá al administrador tener mayor control sobre las versiones, finalmente esa es la principal de Github. Como quiera que sea, toda mi parte ya está terminanda, lista para revisión.
Saludos
