### ISSUE TITLE
Estado de avance

### ISSUE THREAD

**Issue by cvilchesfurio** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#17]
Hola a todos, espero se encuentren bien.

Para su información, les cuento que algunos colegas ya han terminado sus capítulos. En el archivo "TranslationGuide"estoy poniendo la fecha de entrega, además del responsable de la edición y revisión final.  [](https://github.com/Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES/blob/master/TranslationGuide/README.md)

Quisiera saber si alguno ha tenido dificultades de tiempo para avanzar y si necesitan colaboración. También consultarles si estiman necesario que coordine una video-conferencia para la próxima semana para conversar algo que les inquite; o lo dejamos para fines de octubre como inicialmente lo habíamos conversado. Favor cuéntenme sus impresiones.

Aprovecho de dar la bienvenida a Nicolás Alessandroni <nicolas.alessandroni@uam.es> que se ha incorporado al equipo de traducción/edición. 

Nicolás trabaja actualmente en el área de Psicología Cognitiva y Aprendizaje del Depto. de Psicología Evolutiva y de la Educación, de la Facultad de Psicología de la Universidad Autónoma de Madrid. Tiene experiencia en la traducción Inglés-Español de textos académicos y también en edición académica tanto de libros y documentos de trabajo como de revistas científicas de acceso abierto (i.e. Epistemus, Revista de Estudios en Música, Cognición y Cultura). Nicolás mantiene lazos profesionales con Argentina, su país natal, especialmente con la Universidad Nacional de La Plata, donde obtuvo sus títulos de grado y trabajó como docente. Gracias nuevamente Nicolás por tu colaboración, la que se centrará especialmente en edición y revisión final de algunos capítulos.

Quedo atenta a sus comentarios. Un abrazo, Claudia

**Comment by rosariorogel** [comment]
Enterada, mil gracias

**Comment by MpaulaL** [comment]
Bienvenido Nicolás. Gracias Claudia por el mensaje. Me parece que voy avanzando adecuadamente de acuerdo al plazo establecido. Por ahora no siento que necesite ayuda. Además que estoy aprendiendo montones y disfrutando mucho de esta experiencia :-)...No tengo asuntos urgentes que discutir. Un abrazo, Paula

**Comment by pbougeois** [comment]
Perfecto, muchas gracias.
