### ISSUE TITLE
Dudas en la traducción de ciertos términos y frases

### ISSUE THREAD

**Issue by MpaulaL** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#20]
Estimados todos,

Ya terminé la traducción de mi parte y estoy en la última revisón de la versión en espagnol fijándome en la consistencia del uso de palabras y la correcta traducción de éstos y de algunas frases. Tengo algunas dudas y por eso quería pedirles su opinión, quizás ustedes ya adoptaron un término en particular para las siguentes palabras (se viene una lista ;-)):

1. Learner = alumno o estudiante o aprendiz? - yo he usado indistintamente alumno o estudiante, necesito saber si ustedes han usado uno u el otro específicamente para poder estandarizar el texto.
2. 'Software Carpentry'= Carpintería de Software? o dejo sin traducir?
3. 'Connected Curriculum Framework'= Plan de Estudios Conectado? o Currículo Conectado?
4. Software = es necesario traducirlo? Traducir a qué? programa computacional?
5. Code = en el texto se refiere a code en programación - no sé como traducirlo, código no me suena :-/
6. sharing = intercambiar en vez de compratir?
7. audience= Público o audiencia? 
8. Target audience = Público/aundiencia objetivo? Público/aundiencia meta?
9. because a first time yield for all outcomes is almost impossible = lo traduje como: porque un desempeño perfecto para todos los resultados esperados es casi imposible - se entiende?
10. annotated terminologies = terminologías anotadas? o?
11. SMART es un acrónimo que representa cinco criterios: Simple - Medible - Ambicioso - Realista - Temporizado/Cronometrado? (cómo traducir Timed?)
12. summative assessment = evalucaión contínua o evaluación acumulativa?
13. Stick figures are enough to present complex ideas = lo traduje como: Las figuras dibujadas con palitos son suficientes para presentar ideas complejas - se entiende? (05 Examples _ Practical Guidance/05_icebreaker.png)
14. Speaker = orador o presentador
15. Gamification = ludificación o gamificación o sin traducir?
16. engage/engagement= participar/particpación (en vez de comprometer/compromiso) - de acuerdo?
17. check = chequear o verificar?
18. feedback = comentario - de acuerdo? o no se traduce? - la traducción oficial de retroalimentación no me suena para este contexto.
19. gap texts (in the context of exercises) = textos a completar?

Muchas gracias de antemano por su ayuda.
Saludos cordiales,
Paula

**Comment by BenitoCP18** [comment]
Hola buen día Paula, de la parte que me toco a mi solo vienen los siguientes términos, hasta este momento los eh manejado de la siguiente manera:
Learner: Aprendiz
Audience: audiencia 
Target audience: audiencia objetivo
Speaker: orador.
Check: verificar
Feedback: comentario

Y en cuanto a las preguntas y dudas que tienes aquí te pongo algunos comentarios, espero que sean de ayuda:

Me parece que el término software puede quedarse sin traducir, dado que se considera un extranjerismo necesario, ya que su empleo esta muy arraigado en español. En el siguiente enlace la RAE detalla el uso de extranjerismos: [https://bit.ly/1nR1CFh](url) 

La traducción de timed, aparte de temporizado/cronometrado también se puede traducir como programado (aunque la verdad suena un poco extraño). Opcionalmente si se piensa en timed como un adjetivo (ej. well-timed) se podría traducir como prudente, oportuno, pertinente o relevante, que son términos que siento van más apegados a lo que se quiere dar a entender con el acrónimo SMART.

Code si va relacionado a programación se podría traducir cómo código de programación o es mas común encontrarlo como lenguaje de programación.

Summative assessment también podría traducirse cómo la evaluación sumativa, que es un tipo de evaluación que regularmente se lleva a cabo al finalizar un curso y valora los resultados de aprendizaje.

Gamificatión es mayormente conocida, o bueno al menos yo eh leído más veces, el término de gamificación.

Espero esto sea de ayuda, no son todas tus dudas pero entre todos les iremos dando respuesta.
Saludos,
Benito.

**Comment by MpaulaL** [comment]
Muchas gracias Benito! Me ayudas mucho!
En cuanto a 'timed' me hubiese gustado seguir el acronimo smart, pero me parece que no se va a poder. Igual esperaré la opinión de Claudia con respecto a este término. El resto, seguiré tus sugerencias, así ya tenemos estandarizadas tu traducción  y la mía ;-)

Gracias de nuevo.
Saludos,
Paula

**Comment by cvilchesfurio** [comment]
Hola Paula, te cuento que ando en un Congreso fuera de Santiago. Estaré de vuelta el lunes próximo.  En esa semana me pongo al dia y retomo lo del handbook.
Saludos
Claudia

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by ametodico** [comment]
Hola Claudia

Espero te haya ido bien en la charla sobre open advocacy en la ucn. Cuando tendré observaciones sobre la traducción, y o correcciones que hayas hecho?

Gracias

R

__
Laboratorio de Métodos
I3S // Facultad de Ciencias de la Salud
Universidad Central de Chile
Of: (+56)226661609
ORCID: 0000-0001-5058-9309
