### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by pbougeois** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#4]
Buenos días a tod@s! Necesito ayuda para traducir: Book Sprint facilitators.

Tengan un excelente inicio de semana.

**Comment by MpaulaL** [comment]
No creo que sprint pueda traducirse al espagnol. Está difícil la pregunta:-). Sólo como idea, quizás se podría usar el concepto como traducción? 'Facilitadores de la creación colaborativa del libro' - pero es bastante largo..seguiré dándole vueltas...

**Comment by aliciafgomez** [comment]
Buenas, 

siento el retraso en la respuyesta. Yo optaría por "facilitadores de publicación colectiva" o como sugiere Paula, "facilitadores de creación colaborativa de libros". 
Algunas referencias: 
https://www.recursosculturales.com/un-libro-en-5-dias-mediante-la-creacion-colectiva/
https://core.ac.uk/download/pdf/19609146.pdf
https://universoabierto.org/2016/01/10/que-es-y-como-funciona-un-booksprint/

He visto que BookSprint también se utiliza, sin embargo, al estar ligado a una marca o empresa https://www.booksprints.net/, yo intentaríá utilizar el témino en espanol :)

Por cierto, también he visto que se habla de SoopBook como libros colaborativos. 

Abrazos.

**Comment by cvilchesfurio** [comment]
Me inclino por esta traducción de book sprint: 
La forma de un "libro colaborativo" (book sprint) como un proceso de escritura cooperativo, potenció la creatividad y la innovación, y aseguró la producción de un recurso valioso en solo unos pocos días.

Gracias a todos por sus opiniones!
