### ISSUE TITLE
Traducción de prayer room

### ISSUE THREAD

**Issue by BenitoCP18** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#40]
Hola,
Dentro del texto que me toco hay una parte que habla de los espacios que debe tener la sede del evento y menciona estos 3: "maternity room, prayer room and gender neutral washrooms" ¿Prayer room podría ser traducido como oratorio?
Saludos y gracias.

**Comment by s-Hale** [comment]
Si es una capilla del hospital, quizás 'oratorio' esté bien, pero si es una sala para los musulmanes a rezar, quizá 'sala de rezar' es más preciso.

En inglés, la frase 'prayer room' usualmente indica una sala de rezar musulmán.

**Comment by cvilchesfurio** [comment]
Benito, yo lo traduciría como "sala de oración". ¿Te parece?

orar 
1. intr. Dirigirse mentalmente o de palabra a una divinidad o a una persona sagrada, frecuentemente para hacerles una súplica.

rezar 
1. tr. Dirigir a Dios o a personas santas oraciones de contenido religioso.
2. tr. Dicho del clérigo obligado a ello: Recitar el oficio divino vocal u oralmente.
