### ISSUE TITLE
Uso de altas en nombres propios

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#6]
Sugiero usar altas para referir a un nombre propio:

- Ciencia Abierta
- Ciencia Ciudadana
- Acceso Abierto
- Recursos Educativos Abiertos
- Internet

**Comment by MpaulaL** [comment]
Anotado!

**Comment by cvilchesfurio** [comment]
De acuerdo!!
