### ISSUE TITLE
Ayuda de Tradución: "Patient Innovation"

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#7]
Cómo traducir “Patient Innovation” (capítulo 10, Rational, 1er párrafo, línea 8).

**Comment by cvilchesfurio** [comment]
Rosario, yo pondría "Innovación para el paciente" entre comillas y el concepto en inglés entre paréntesis (*). 
Nota a pié de página:
(*) Información añadida a la versión en español. Iniciativas orientadas a pacientes y quienes se preocupan por ellos, para que puedan compartir y acceder a soluciones útiles e innovaciones que hagan frente a sus enfermedades.
Ejemplos del concepto en:
Join Patient Innovation community https://patient-innovation.com/
https://fipse.es/innovacion-centrada-en-paciente

¿Qué les parece a los demás?

**Comment by rosariorogel** [comment]
Ya lo apliqué.
Gracias
