### ISSUE TITLE
Uso de la segunda persona del singular:

### ISSUE THREAD

**Issue by rosariorogel** [Open-Science-Training-Handbook/Open-Science-Training-Handbook_ES#8]
Sugiero que la traducción usemos la segunda persona del singular (tú), para hacerlo un texto más cercano al público, en lugar de un impersonal o tercera persona del singular/plural usted/ustedes.

¿Ustedes cómo están traduciendo?

**Comment by MpaulaL** [comment]
Yo estoy usando la segunda persona singular cuando se refiere a you, yourself, etc.

**Comment by cvilchesfurio** [comment]
Ok, dejemos entonces  segunda persona, en un estilo más cercano e informal. @Paloma yo reviso y arreglo lo que hayas avanzado. Gracias por lo comentarios!

**Comment by PALOMA** [comment]
Disculpe no entiendo el correo... Creo que se equivoco slds
